services:

  nest-postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - '$DEV_DATABASE_EXTERNAL_PORT:$DEV_DATABASE_PORT'
    environment:
      POSTGRES_DB: $DEV_DATABASE_NAME
      POSTGRES_USER: $DEV_DATABASE_USER
      POSTGRES_PASSWORD: $DEV_DATABASE_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: md5
    networks:
      - nestjs-network
    volumes:
      - ./docker/database:/var/lib/postgresql/data

  nest-postgres-manager:
    image: dpage/pgadmin4
    container_name: postgres-manager
    ports:
      - "$DEV_PGADMIN_PORT:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $DEV_PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DEV_PGADMIN_DEFAULT_PASSWORD
    volumes:
       - ./docker/pgadmin4/servers.json:/pgadmin4/servers.json
    networks:
      - nestjs-network
    depends_on:
      - nest-postgres

  nest-nginx:
    image: nginx:stable-alpine
    container_name: nest-nginx
    ports:
      - "$DEV_NGINX_PORT:80"
    networks:
      - nestjs-network
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.dev.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nest-js

  nest-js:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nest-js
    volumes:
      - ./app:/var/www/html
      - ./docker/keys/:/var/www/html/keys/
      - /app/node_modules/:/var/www/html/node_modules/
      - nest-modules:/var/www/html/node_modules/
    depends_on:
      - nest-postgres
    networks:
      - nestjs-network

networks:
  nestjs-network:

volumes:
  nest-modules: